package eu.trentorise.game.model

rule "ch_leaderboard_position"
no-loop
	salience -2000
when
	$challenge : ChallengeConcept( modelName == "leaderboarPosition", $weekClassificationName: fields["weekClassificationName"], $posMin: fields["posMin"], $posMax: fields["posMax"], $bonusPointType : fields["bonusPointType"], $bonusScore : fields["bonusScore"], isCompleted() != true )
    Classification( name == $weekClassificationName, position >= (Integer)$posMin, position <= (Integer)$posMax)
	$pc : PointConcept(name == (String) $bonusPointType)
then
	log("leaderboard_position COMPLETED");
	$challenge.completed();
	$pc.setScore($pc.getScore() + (Double) $bonusScore);
	update($pc);
	update($challenge);
end
