package eu.trentorise.game.model

rule 'ch_percentageIncrement_check'
when
	$challenge : ChallengeConcept( modelName == "percentageIncrement", $counter: fields["counterName"], $target: fields["target"], $periodName: fields["periodName"] , $bonusPointType : fields["bonusPointType"], $bonusScore : fields["bonusScore"], isCompleted() != true )
	$pc1 : PointConcept(name == (String) $counter, getPeriodCurrentScore((String)$periodName) >= $target)
	$pc : PointConcept(name == (String) $bonusPointType)
then
	log('percentageIncrement COMPLETED');
	$challenge.completed();
	$pc.increment((Double) $bonusScore);
	update($pc);
	update($challenge);
end