//created on: Oct 24, 2016
package eu.trentorise.game.model


rule "green leaves for user registration rule"
lock-on-active
when
	Action( $id : id == 'checkin_new_user_Trento_Fiera' ) 
	$pc : PointConcept(name == "green leaves")
	$cd: CustomData($reg : this['checkin_new_user_Trento_Fiera'] != true)
then
	$pc.setScore($pc.getScore() + 50);
	$cd.put('checkin_new_user_Trento_Fiera',true);
	update($pc);
	log("green leaves for user registration rule COMPLETED");		
end
