package eu.trentorise.game.model
import eu.trentorise.game.core.Utility;

//declare any global variables here
global Utility utils;

rule 'final_survey_check'
when
	Action(id == 'survey_complete')
	$pc : PointConcept(name == "green leaves")
	$cd: CustomData(this['final_survey_complete'] != true)		
then
	utils.log('final survey COMPLETED');
	$pc.setScore($pc.getScore() + 350d);
	$cd.put('final_survey_complete',true);
	update($cd);
	update($pc);
end